version: '3.2'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app/backend
    ports:
      - '8000:8000'
    stdin_open: true
    tty: true
    command: python3 manage.py runserver 0.0.0.0:8000
    environment:
      - DB_HOST=db
      - DB_NAME=backend
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
    depends_on:
      - db
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      # One-way volume to use node_modules from inside image
      - /app/node_modules
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    command: yarn start
  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=backend
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
